version: '3'
services:
  _app_base: &_app_base
    build:
      context: ./
      dockerfile: Dockerfile

  zk-react-admin:
    <<: *_app_base
    command: npm run start
    ports:
      - 3000:3000

  lint:
    <<: *_app_base
    command: npm run lint

